services:
  mysql-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: tienda_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  backend:
    build: ./demo
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/tienda_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: matra-318R

  frontend:
    build: ./mi-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend